id: 1
dbPath: ./_output/icecanekv/1/
address: 127.0.0.1
port: 9000
peers:
  -
    id: 2
    address: 127.0.0.1
    port: 9000
  - 
    id: 3
    address: 127.0.0.1
    port: 9000
  - 
    id: 4
    address: 127.0.0.1
    port: 9000
