FROM golang:1.15

LABEL AUTHOR="Saurav Tiwary (srv.twry@gmail.com)"

# copy app
ADD . /app
WORKDIR /app

RUN go mod download
RUN go get github.com/githubnemo/CompileDaemon

# server running port
EXPOSE 9000

ENTRYPOINT CompileDaemon -build="go build -o kv -v ./cmd/icecanekv/" -command="./kv"
