package icecanesql

import "github.com/dr0pdb/icecanedb/pkg/frontend"

// PlanNode is the query execution plan generated by the planner
// It is used by the executor to execute the query.
type PlanNode interface{}

var _ PlanNode = (*CreateTablePlanNode)(nil)

// CreateTablePlanNode is the planner node for the create table query
type CreateTablePlanNode struct {
	Schema *frontend.TableSpec
}
