package icecanesql

import "github.com/dr0pdb/icecanedb/pkg/frontend"

// PlanNode is the query execution plan generated by the planner
// It is used by the executor to execute the query.
type PlanNode interface{}

var _ PlanNode = (*CreateTablePlanNode)(nil)
var _ PlanNode = (*DropTablePlanNode)(nil)
var _ PlanNode = (*TruncateTablePlanNode)(nil)
var _ PlanNode = (*BeginTxnPlanNode)(nil)
var _ PlanNode = (*FinishTxnPlanNode)(nil)

// CreateTablePlanNode is the planner node for the create table query
type CreateTablePlanNode struct {
	Schema *frontend.TableSpec
}

// DropTablePlanNode is the planner node for the drop table query
type DropTablePlanNode struct {
	TableName string
}

// TruncateTablePlanNode is the planner node for the truncate table query
type TruncateTablePlanNode struct {
	TableName string
}

type BeginTxnPlanNode struct {
	ReadOnly bool
}

type FinishTxnPlanNode struct {
	IsCommit bool
}
